# Generated by Django 4.0.4 on 2022-05-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('birth_date', models.DateField(verbose_name='Date')),
                ('password1', models.CharField(max_length=25, verbose_name='Password')),
                ('password2', models.CharField(max_length=25, verbose_name='Password')),
            ],
        ),
    ]
